# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-29 08:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBundledQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(blank=True, max_length=255, null=True)),
                ('class_name', models.CharField(blank=True, max_length=255, null=True)),
                ('field', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('path_info', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('app_name', models.CharField(max_length=255)),
                ('default', models.BooleanField(default=False)),
                ('ordering', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255)),
                ('criteria', models.CharField(blank=True, max_length=255, null=True)),
                ('is_multiple', models.BooleanField(default=False)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='adminfilters.CustomFilter')),
            ],
        ),
        migrations.AddField(
            model_name='custombundledquery',
            name='custom_filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundled_queries', to='adminfilters.CustomFilter'),
        ),
    ]
